---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myapp-db-secret
  namespace: myapp-staging
spec:
  encryptedData:
    DB_PASSWORD: AgBg5/OwQRJbPFmulYLKoEgGMjfqRRzP/asx4ZIv3qQFYK9AcilAejvBJkHIWNOICVI2QKvzmRTIk6SdOgCXPeg2YLLJB4+aSmPpFqrrn43OTrkkxzdLk36+V/kPf83pCP1fQisICHi78u4iP9LAKbKYvq+SwW4YrqZik1/4gw3Pe1R9gs2r8w1Goy8r/W+V8xQF0tkOkphpx1XZ4jS+TX8OU8sZQ92f5CGIaF7NfRdb1BQLhEQ6Pd4j/XTEmX3ghBwfhCcR8wHK/6EGVmP5cks3aZUzSdJnqk3pA7cAIpBFnPGBFpC28Ts+fv9bhqc/58QqjYu8gFlESkLBaBesplzVljoYyPuycZw8Nz191guFzdzJITh7393E0I0GVxWm6WSk1JqKV9O26yigzstoTCr1w/rvab8dYlUtAE+gOW7t8dEV/2XpCpCRVgfm2ZwhGtaNf4B4hWDZFSfDu4wBE+Gw5K/chz2gnFqya0jGAWMwWl54j92PEFzkdKE2sn44uPSoKXRCnCbMDxX8OSHQy/83kO8ItzZwjcJyMQPnZOeQk7lFMJf3RSQVJL5vugUjkEqygxZnIzRaXR7LptONtnQfQ1tGVc+wQ28jU7ElIm4kFYxQIHZZeW3OrJi5USY8PmOqJq6/rTYxsnzCHbjXx/g3F3MZ/vdBxV/eSOIo1BFaN0bSRVXQCiMnEGfh0PFGBw+WtGMQFnceIm6hsw==
  template:
    metadata:
      creationTimestamp: null
      name: myapp-db-secret
      namespace: myapp-staging
