---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myapp-db-secret
  namespace: myapp-dev
spec:
  encryptedData:
    DB_PASSWORD: AgCHNng/F9WC5QPZFyL1gGisBpTcKjsipgDgbensEoULP3QUHue0LkL6iMQu7k6gE9nlc4n4yF9HFLDGrVPMADfIFEivx3ot6QVH3fVNUloX6BpeRBStSaxcTqtiTdMS9fhuobzx2pShdo1boU8pnVeSuJcQ3yBAHYqW5xCzxwtuA7qi3CliE+RrRWnV04MG0VaVTXjI2HNBp0+v689Kl8iej8DHpRAGgp24JQWvTnwZOrLK8rh/05Z480nSlndLZ6wbL3TZ+dR+yZ1d1dHHFtz2SDcmaVEXjzGfTdvLHN7fXGb2KQl3XVQzlQsVJC3Hk8feJteHDN+Jscibacfn9cw+LY4gus69VTXKU/FTHgn2Da3doIpndElex/8k46ks1uGgOHvPoDKEi9fAEQIFF9Dt21SktdF1AUAbR7rLsxaW7JvZh3xSmnwW7vVkIUii9BRXtXOiHoi1FfxVVuN/3iswoxyVArv/4LbHwy3HoKfYa5Jd/BQoK38H6w7Yc/udiarTl5t+OwVbYPTPMZy62ZJbEKTHJrYF40F3M+C0cg5w6v7uwNM8dJlkmNB6ZS7lutI/Xvw6aXHHqojYv903XYm6HleC72C/6UifNV2SqPavSulUBUI6fS84/zQfLPJbB/GX1UH88HMhql4Y1xYG+qmAVEizpFsij75HrMwHWD2NM2/9QJccst3PzBK3fFMYSuyCGLUsARNN8VddZw==
  template:
    metadata:
      creationTimestamp: null
      name: myapp-db-secret
      namespace: myapp-dev
