---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myapp-db-secret
  namespace: myapp-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAecc7Chxyc0JtNCF2xjlS3+kCip7iB+xOfYbo9gZEbtyEUZEG/0SfOYF1RMMlmJ7ySXOkK0934vnFnowxq5Id/WWsRA+NGFpSj3SkJx75OKySdZdX50ZuFS9NlxEyAIuF0YN105tv/pmXuNJ/HynV/DK8l/doJK4YBspcck4bARQXLuIM/vOQA8j4Fz9vnrJqK49u6YeR7WMZK9VJLwjgYy33WRQK60tgWEDmqkwJ1ZmG2jM4MO4GQ9r224k3Y+c8ubZh7X/KMMvSEc+IiuJq8XHKb1CKdzNqVKC5C8YSYXnRFxWbeKwdNGOLgtn85y/gBpIkcSAXL2Xs4sRUMyyCHxWFvF2SzqQTj6OXbwaqCSVuPI4i/bC+jqna1nbAVoD4bUyuTc8Mz6QiAsgbCQZFMpgu3u6oEZMcrLpSHWFxUR9fFAf1UDSM6quHuY9s++4V4KIYQlWIk+OY3fsFyrajFjbggpz6iIiNpQUpmzN+0jHNszA+7MCSSVYqNmLHGI+kPl1dJ42gxAYj6HaVteVeBJOcK3Xlzrj6r6fLv0elTgJvaYvlcP8g8h8ske78LMDO8uePA8O9Qnmp+O6gKCjHk/7kNc9de52QI6EqJ7NM1ZssgmiXA6JhTL9AC0/V0N+pmkZ9tpTcuDjzWPdip5feKbP50Q7iaCGSgQIAhD6DnHcLUWF9781DbOYEGNbFkJa0jecRjPnmsh7qGlA==
  template:
    metadata:
      creationTimestamp: null
      name: myapp-db-secret
      namespace: myapp-prod
